# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: yo-jekyllrb
description:
author:
  name: Amitai Burstein
  email: amitai@gizra.com

# Grunt handles images and assets.
exclude: ['images', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

include: ['.htaccess']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

# Markdown library
markdown: redcarpet
redcarpet:
  extensions: ['fenced_code_blocks', 'tables', 'smart']

pygments: true

title : Gizra
excerpt_separator: "<!-- more -->"

paginate: 10
paginate_path: "blog/page:num"

url: http://www.gizra.com

authors:
  - amitaibu:
      name: Amitai Burstein
      title: CTO, Co-Owner
      is_member: true
      bio: Maintainer of Organic groups, the Message stack, and co-maintainer of Drupal 8's Entity reference. <a href="/content/the-about-story/">The about story</a>.
      email: amitai@gizra.com
      twitter: amitaibu
      github: amitaibu
      avatar: amitaibu.jpg
      image: amitaibu.jpg
  - bricel:
      name: Brice Lenfant
      title: CEO, Co-Owner
      is_member: true
      bio: Brice leads strategy, and helps run projects at Gizra. He works closely with both the team and customers to strategize and develop the project end-to-end and coordinate project needs and delivery.
      email: brice@gizra.com
      twitter: briceAtGizra
      github: bricel
      avatar: bricel.jpg
      image: bricel.jpg
  - niryariv:
      name: Nir Yariv
      title: CPO
      is_member: true
      bio: Messed with PHP since before it was cool, and for some time after. Now mostly herds cats.
      email: nir@gizra.com
      twitter: niryariv
      github: niryariv
      avatar: niryariv.jpg
      image: niryariv.jpg
  - OritiMG:
      name: Orit Geron
      title: Operations Manager
      is_member: true
      bio: I speak fluent geek, and can translate to human speaking
      email: orit@gizra.com
      twitter: OritiMG
      github: OritGeron
      avatar: OritGeron.jpg
      image: OritGeron.jpg
  - HelenaEksler:
      name: Helena Eksler
      title: Team Lead
      is_member: true
      bio: Cooking well, doesn't matter - dinner or code.
      email: helena@gizra.com
      github: HelenaEksler
      avatar: HelenaEksler.jpg
      image: HelenaEksler.jpg
  - bitamar:
      name: Itamar Bar-Lev
      title: Team Lead
      is_member: true
      bio: Something about Itamar
      email: itamar@gizra.com
      github: bitamar
      avatar: male.jpg
      image: bitamar.jpg
  - IshaDakota:
      name: Adam Stewart
      title: USA CTO
      is_member: true
      bio: If I'm not here, I'm at Wrigley Field.
      email: adam@gizra.com
      twitter: adamhstewart
      github: IshaDakota
      avatar: IshaDakota.jpg
      image: ishadakota.jpg
  - kazabooboo:
      name: Adar Earon
      title: USA Director
      is_member: true
      bio: I don't really need tips on how to fall asleep. I have twins.
      email: adar@gizra.com
      twitter: kzbooboo
      github: kazabooboo
      avatar: kazabooboo.jpg
      image: male.jpg
  - NaderSafadi:
      name: Nader Safadi
      title: Team Lead
      is_member: true
      bio: Show me the source code and I'll be happy!
      email: nader@gizra.com
      github: nader77
      avatar: nedSaf.jpg
      image: nedSaf.jpg
  - RoySegall:
      name: Roy Segall
      title: Team Lead
      is_member: true
      bio: Not afraid of patching Organic groups, Entity reference or the Message stack. Knows how to make tasty Pizza.
      email: roy.segall@gizra.com
      github: RoySegall
      avatar: RoySegall.jpg
      image: RoySegall.jpg
  - Moo64c:
      name: Amir Arbel
      title: Developer
      is_member: true
      bio: Something about Amir
      email: amir@gizra.com
      github: Moo64c
      avatar: male.jpg
      image: male.jpg
  - ordavidil:
      name: Or David
      title: Developer
      is_member: true
      bio: Something about Or
      email: or@gizra.com
      github: ordavidil
      avatar: male.jpg
      image: ordavidil.jpg
  - DavidKohav:
      name: David Kochav
      title: QA Engineer
      is_member: true
      bio: There are no shortcuts in life, Do what is necessary, Everything matters!.
      email: david@gizra.com
      github: DavidKohav
      avatar: male.jpg
      image: DavidKohav.jpg
  - shahardo:
      name: Shahar Dolev
      title: Developer
      is_member: true
      bio: Something about Shahar
      email: shahar@gizra.com
      github: shahardo
      avatar: male.jpg
      image: male.jpg
  - YaronMiro:
      name: Yaron Miro
      title: UX/UI Developer
      is_member: true
      bio: There are no shortcuts in life, Do what is necessary, Everything matters!.
      email: yaron@gizra.com
      github: YaronMiro
      avatar: YaronMiro.jpg
      image: YaronMiro.jpg
  - NirGalon:
      name: Nir Galon
      title: Developer
      is_member: true
      bio: A geek who always want to learn new things.
      email: nir.galon@gizra.com
      github: nirgn975
      avatar: NirGalon.jpg
      image: NirGalon.jpg
  - Pavel:
      name: Pavel Pirozhenko
      title: Developer
      is_member: true
      bio: A geek who always want to learn new things.
      email: pavel@gizra.com
      github: ppavels
      avatar: PavelPirozhenko.jpg
      image: Pavel.jpg
  - GuyTepper:
      name: Guy Tepper
      title: Developer
      is_member: true
      bio: Somthing about Guy.
      email: guy.tepper@gizra.com
      github: guytepper
      avatar: GuyTepper.jpg
      image: Guy.jpg
  - RachelBaram:
      name: Rachel Baram
      title: Business Development & Marketing
      is_member: true
      bio: Loves to make things make sense.
      email: rachel@gizra.com
      github: RachelBaram
      avatar: RachelBaram.jpg
      image: RachelBaram.jpg
  - itamarbu:
      name: Itamar Burstein
      title: Industrial Designer
      is_member: false
      bio: My designs have been endorsed by companies such as VIA France, Roche Bobois, Metalarte, Ligne Roset & Jofebar. That's pretty awesome.
      avatar: itamarbu.jpg
  - ceoaliongroo:
      name: Carlos Mantilla
      title: Full stack developer
      is_member: false
      bio: AngularJs, d3js, nodejs. Everythis JS!
      avatar: ceoaliongroo.jpg
  - lukeherrington:
      name: Luke Herrington
      title: Developer
      is_member: false
      bio: Luke is just another web nerd that loves to learn new technologies. He works at Qualcomm by day as a software application engineer and hangs at home by night as a dad and husband.
      avatar: lukeherrington.jpg
